version: "3.3"

services:

  database:
    build:
      context: .
      dockerfile: build/db.Dockerfile

  main:
    build:
      context: .
      dockerfile: build/main.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database

